name: CD
run-name: ${{ github.event.client_payload.ref_name || github.ref_name }}
on:
  repository_dispatch:
    types:
      - new-deployment
  workflow_dispatch:
    inputs:
      debian:
        description: Run builds only on debian
        type: boolean
jobs:
  prepare:
    if: ${{ cancelled() == false && failure() == false && (github.event.client_payload.tag || inputs.debian != false) }}
    runs-on:
      - homelab
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup packer
        uses: hashicorp/setup-packer@v3
        with:
          version: "1.12.0"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packer
          path: ${{ github.workspace }}

  build-debian:
    if: ${{ cancelled() == false && failure() == false }}
    name: Build Debian (${{ matrix.pve_node.name }})
    needs:
      - prepare
    runs-on:
      - ubuntu-latest
    defaults:
      run:
        working-directory: "${{ github.workspace }}/debian"
    strategy:
      fail-fast: true
      matrix:
        pve_node:
          - alpha
          # - beta
          # - tango
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: packer
          path: ${{ github.workspace }}

      - name: Init Packer
        run: |
          packer init .

      - name: Build image
        run: |
          packer build \
            -var "proxmox_node=${{ matrix.pve_node }}" \
            -var "proxmox_host=${{ secrets.PROXMOX_HOST }}" \
            -var "proxmox_api_user=${{ secrets.PROXMOX_API_USER }}" \
            -var "proxmox_api_password=${{ secrets.PROXMOX_API_TOKEN }}" \
            -var-file variables.pkrvars.hcl \
            .
