name: CI
on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      force-build:
        default: false
        description: Running manual build
        type: boolean
        required: false

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  packer-validate:
    name: Lint Packer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup packer
        id: setup
        uses: hashicorp/setup-packer@v3
        with:
          version: "1.12.0"

      - name: Prepare dummy variables
        run: |
          # Root
          echo 'proxmox_host="proxmox.pl"' >> test.pkrvars.hcl
          echo 'proxmox_api_user="user@pve"' >> test.pkrvars.hcl
          echo 'proxmox_api_password="password"' >> test.pkrvars.hcl
          # Dynamic
          echo 'proxmox_node="alpha"' >> test.pkrvars.hcl

      - name: Init Packer
        id: init
        working-directory: "${{ github.workspace }}/debian"
        run: |
          packer init .

      - name: Run validate
        id: validate
        working-directory: "${{ github.workspace }}/debian"
        run: |
          packer validate -var-file ../test.pkrvars.hcl -var-file variables.pkrvars.hcl *.pkr.hcl
